name: CI

on: push

jobs:
  healthcheck:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/checkout@v3
      - name: Cache Haskell dependencies
        id: cache-stack
        uses: actions/cache@v3
        with:
          path: ~/.stack
          key: ${{ runner.OS }}-haskell-cache-${{ hashFiles('**/stack.yaml') }}
          restore-keys: |
            ${{ runner.OS }}-haskell-cache-

      - if: ${{ steps.cache-stack.outputs.cache-hit != 'false' }}
        name: Verify if data already in cache
        continue-on-error: true
        run: |
          echo "DATA WAS ALREADY CACHED !"

      - if: ${{ steps.cache-stack.outputs.cache-hit != 'true' }}
        name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: '8.8'
          cabal-version: '3.0.0.0'

      - name: Install Stack
        run: |
          sudo apt-get -y update && curl -sSL https://get.haskellstack.org/ | sh
          export PATH="$HOME/.local/bin:$PATH"

      - name: Build Project
        run: make

      - name: Test the project
        run: make tests_run